CREATE TABLE IF NOT EXISTS PERSONS (
    ID  INTEGER AUTO_INCREMENT,
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(128),
    CITY VARCHAR(128),
    ZIP INTEGER,
    PHONE_NUMBER VARCHAR(128),
    MAIL VARCHAR(128),
    PRIMARY KEY (ID)
);