CREATE TABLE IF NOT EXISTS PERSON (
    ID  INTEGER AUTO_INCREMENT,
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(128),
    CITY VARCHAR(128),
    ZIP INTEGER,
    PHONE_NUMBER VARCHAR(128),
    MAIL VARCHAR(128),
    MEDICAL_ID INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS FIRESTATION (
  ID_STATION INT NOT NULL,
  CONSTRAINT PK_FIRESTATION PRIMARY KEY (ID_STATION)
);

CREATE TABLE ATTACHED_ADDRESS(
   FIRESTATION_ID_STATION INTEGER,
   ADDRESS VARCHAR(128)
);

