CREATE TABLE IF NOT EXISTS PERSONS (
    ID  INTEGER AUTO_INCREMENT,
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(128),
    CITY VARCHAR(128),
    ZIP INTEGER,
    PHONE_NUMBER VARCHAR(128),
    MAIL VARCHAR(128),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS FIRESTATIONS (
  ID_STATION INT NOT NULL,
  CONSTRAINT PK_FIRESTATIONS PRIMARY KEY (ID_STATION)
);

CREATE TABLE ATTACHED_ADDRESSES(
   FIRESTATION_ID_STATION INTEGER,
   ADDRESSES VARCHAR(128)
);